version: '3'
services:
  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: git_land
    networks:
      - webnet
    # volumes:
    #   - ./my_dbdata.tx:/var/lib/postgresql
  web:
    restart: always
    build: .
    ports:
      - "22:22"
    depends_on:
      - database
    links:
      - database
    networks:
      - webnet
 
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 8082:80
    command: /bin/bash -c "cat /etc/nginx/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - webnet
    depends_on:
      - web

networks:
    webnet:
