# Generated by Django 2.2.3 on 2019-07-19 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, null=True)),
                ('repo_path', models.FilePathField(unique=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_id', models.CharField(max_length=100)),
                ('commit_message', models.TextField()),
                ('test_exit_code', models.IntegerField()),
                ('log', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='git_land.Repository')),
            ],
        ),
        migrations.CreateModel(
            name='Ssh_key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=50)),
                ('ssh_key', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
