# Generated by Django 2.2.3 on 2019-07-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_land', '0002_auto_20190715_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssh_key',
            name='ssh_key',
            field=models.CharField(max_length=10000),
        ),
    ]
