# Generated by Django 2.2.3 on 2019-07-17 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('git_land', '0004_auto_20190717_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_info',
            name='repo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='git_land.Repository'),
        ),
    ]
