# Generated by Django 2.2.3 on 2019-07-18 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('git_land', '0004_auto_20190718_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_info',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
