# Generated by Django 2.2.3 on 2019-07-17 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('git_land', '0005_auto_20190717_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='name',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='test_info',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
