# Generated by Django 2.2.3 on 2019-07-17 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('git_land', '0006_auto_20190717_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_info',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
